version: '3.4'
services:
    node:
        image: node:lts-alpine
        working_dir: /app
        ports:
            - "3030:3030"
        volumes:
            -   .:/app
        stdin_open: true # docker run -i
        tty: true
